Add CSS Variables RFC
vtex-apps/rfcs pull request #3
Opened 2020-03-31 19:05 UTC by klzns

2020-03-31 19:08 UTC, kaisermann approved these changes

2020-03-31 20:07 UTC, iaronaraujo requested changes

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +- Start Date: 2020-03-31
```suggestion
# RFC CSS Variables

- Start Date: 2020-03-31
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Summary
```suggestion
## Summary
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Basic example
```suggestion
## Basic example
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Motivation
```suggestion
## Motivation
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Detailed design
```suggestion
## Detailed design
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Drawbacks
```suggestion
## Drawbacks
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Alternatives
```suggestion
## Alternatives
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Adoption strategy
```suggestion
## Adoption strategy
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# How we teach this
```suggestion
## How we teach this
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +# Unresolved questions
```suggestion
## Unresolved questions
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +Compiling the Tachyons with `compileVars: false`, it will make it possible to reference those variables in CSS.
```suggestion
Compiling the Tachyons with `compileVars: false` will make it possible to reference those variables in CSS.
```

2020-03-31 20:07 UTC, iaronaraujo commented on text/0003-css-variables.md
> +CSS Variables does not work in IE11 so we need to add a polyfill: https://github.com/nuxodin/ie11CustomProperties.
```suggestion
CSS Variables does not work in IE11 so we need to add a [polyfil](https://github.com/nuxodin/ie11CustomProperties).
```

2020-03-31 20:14 UTC, iaronaraujo approved these changes

2020-04-06 17:09 UTC, kaisermann approved these changes

2021-10-22 19:43 UTC, closed without merging